# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04405656ecb4c1b25b78cb73559f9d05eeb3f9b7318d8ccb5b9b8fa44eebeb44daf6d2c516f43d5edabe9424e06fc91d87a0146ccd3644b305abece14568c8e5

test:
  secret_key_base: 8ad5febd75cbb15a105e1c6e2f360ac6d24518fc97c4970fbd23899c9e6ad4bf485dcabd082d0f87be23984b6a06e7f9c13496d98da864d9153c18558724fef0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
